export const SHARED_SETTINGS_PROVIDER_TOKEN = 'SHARED_SETTINGS_PROVIDER_TOKEN';
export const EXTERNAL_AUTH_PROVIDER_TOKEN = 'EXTERNAL_AUTH_PROVIDER_TOKEN';
export const EXTERNAL_CLIENT_FACTORY_TOKEN = 'EXTERNAL_CLIENT_FACTORY_TOKEN';
