export const REPORT_REGISTRY_TOKEN = 'REPORT_REGISTRY_TOKEN';
export const SIMPLE_SALES_SUMMARY_XLSX_DATASET_ROTATION_TOKEN =
  'SIMPLE_SALES_SUMMARY_XLSX_DATASET_ROTATION_TOKEN';
export const REPORT_INSTANCE_STORE_TOKEN = 'REPORT_INSTANCE_STORE_TOKEN';
export const REPORT_INSTANCE_RUNNER_TOKEN = 'REPORT_INSTANCE_RUNNER_TOKEN';
export const REPORT_JOB_QUEUE_TOKEN = 'REPORT_JOB_QUEUE_TOKEN';
